# Instructions to run:
# 1. cd to folder containing this file
# 2. $ conda env create --force
# 3. $ source activate dl
name: dl
channels:
  - conda-forge
  - damianavila82
dependencies:
  - python == 3.6
  - jupyter
  - rise
  - pip:
    - tensorflow == 1.0
    - keras == 2.0
